name: Continuous Integration

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]

concurrency:
  group: "main"
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.17
          apps: scala-cli

      - run: scala-cli --power compile .

  deploy:
    name: Deploy app
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: production
      url: "https://smithy-selector-playground.fly.dev/"

    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.17
          apps: scala-cli

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kubukoz
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
      - run: |
          scala-cli --power package --docker .

          export DOCKERHUB_ALIAS=kubukoz/smithy-selector-playground:latest
          export FLY_ALIAS=registry.fly.io/smithy-selector-playground:latest

          docker push "$DOCKERHUB_ALIAS"
          docker tag "$DOCKERHUB_ALIAS" "$FLY_ALIAS"
          docker push "$FLY_ALIAS"

        env:
          PUBLISH_OFFICIAL: "true"
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
